### ISSUE TITLE
What is the purpose of the create* scripts?

### ISSUE THREAD

**Issue by mattcollier** [ch-nry/VCV_nozori#10]
Hello, building the project to troubleshoot issues with pitch module.

If I run the `create_all.sh` script, one adverse effect is that it copies a `plugin.json` file with an old version tag of 1.1.2 in it.

https://github.com/ch-nry/VCV_nozori/blob/master/template_nozori/plugin.json#L4

I have subsequently learned that it is not necessary to run the script at all to make a successful build.

What is the purpose of the create scripts?

**Comment by ch-nry** [comment]
Initially, I write nozori code fas a hardware project : https://github.com/ch-nry/nozori
Then, I change some file in order to compile the code for VCVrack. Since the modification are the same for all modules, I create a script to "convert" the initial code to VCV code.
You need to run the script if you change a file in the template folder in order to generate the project that can be compiled. 
The plugin.json have been modified manually to add tag to modules.
If you want to update the code for only 1 module, then there is no need to use this script.
