### ISSUE TITLE
Make it clearer that a specific sampling rate is required, so that users won't install modules they can't use

### ISSUE THREAD

**Issue by pixelrust** [ch-nry/VCV_nozori#16]
Most VCV modules don't require any specific sampling rate. When installing a new module, users will reasonably expect it's going to work at any given sampling rate. They could get negatively surprised to to find out it's not the case. According to https://github.com/ch-nry/VCV_nozori most Nozori modules "need a 96KHz sampling rate. Few others need 48KHz sampling rate. Using another frequency is not recommended".

Is there any way to make such requirements and recommendations clearer, in order to prevent users to subscribe, download and install modules they won't be able to use?
Maybe the required or recommended sampling rate could be embedded in the name of the module?

**Comment by ch-nry** [comment]
As a VCV user, I download, install, test and uninstall lot's of modules! 
Since nozori modules are free, I don't see any problem.
This limitation is clearly stipulate on the documentation. If you don't read the documentation, there are lot's other module that will not work as you can expect.

Nozori modules for VCV use exactly the same code as the hardware module. Knowing this, users should expect them to run on a fixed SR. 
Moreover, you still can use the module even if you're using the wrong SR.

Having the SR in the name is not possible since you download more then 40 modules on the same time.

All in all, I don' see any problem, and I don't see any way to improve things. but I'm still open to other suggestions.

**Comment by pixelrust** [comment]
Got it! Thanks for your reply. I guess I can close this.
