### ISSUE TITLE
Very Processor-Intensive

### ISSUE THREAD

**Issue by jonheal** [ch-nry/VCV_nozori#5]
Your modules are very interesting. I want to use them, but I can't. At 96k, they completely overwhelm my i7-3770, even with a 2048 block size on my PreSonus audio interface. The sound breaks up terribly.

I hope you can find a way to make your modules less processor-intensive, because I really want to explore them. :)

**Comment by ch-nry** [comment]
Thanks for your interest in my modules, I'm sorry to hear that they are to processor-intensive. 
They have been developed and optimized on ARM processor running at 80Mhz for high performance and very low latency. 
I port them to VCV Rack because it was easy and would allow people to test them before buying the hardware. Optimizing them for VCV Rack would need a complete rewrite of all modules. 
For multiples reasons (time, money etc), I have no plan to do this. 
You can still use them at lower frequency : they will work even if few things will not be tuned like the originals.
